;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --memory64-lowering -S -o - --enable-memory64 | filecheck %s

(module
  (memory i64 1)
  (func (export "test") (result i32)
    (i32.load offset=4294967300 (i64.const 0))
  )
)
;; CHECK:      (module
;; CHECK-NEXT:  (type $0 (func (result i32)))
;; CHECK-NEXT:  (memory $0 1)
;; CHECK-NEXT:  (export "test" (func $0))
;; CHECK-NEXT:  (func $0 (result i32)
;; CHECK-NEXT:   (i32.load offset=4
;; CHECK-NEXT:    (i32.wrap_i64
;; CHECK-NEXT:     (i64.add
;; CHECK-NEXT:      (i64.const 0)
;; CHECK-NEXT:      (i64.const 4294967296)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )
